# Generated by Django 5.2.5 on 2025-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='daily_goals',
            field=models.IntegerField(default=1),
        ),
    ]
