# Generated by Django 5.2.5 on 2025-10-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
